# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: pihole
  namespace: default
type: Opaque
stringData:
  FTLCONF_webserver_api_password: yourpasswd