apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: netbird-up
  namespace: default
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: me # Must match the name of your main GitRepository resource
  git:
    checkout:
      ref:
        branch: main # Change this to the branch you want Flux to commit to
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "chore(infra): automated update of NetBird to {{ .SelectedTarget.Tag }}"
    push:
      branch: main
  update:
    path: "./netbird/" # The directory path in Git where your NetBird deployment file lives
    strategy: Setters
