apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: netbird
  namespace: default
spec:
  image: netbirdio/netbird
  interval: 1h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: netbird-latest
  namespace: default
spec:
  imageRepositoryRef:
    name: netbird
  policy:
    alphabetical:
      order: asc # Keeps track of the underlying sha256 changing on the 'latest' tag
