# kubectl create configmap nginx --from-file=./nginx.conf
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-r-p
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8090
          name: http
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        env:
        - name: TZ
          value: "Asia/Kolkata"
      volumes:
      - name: config
        configMap:
          name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
