# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: default
  labels:
    app: adminer
spec:
  selector:
    matchLabels:
      app: adminer
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  adminer
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: adminer
        volumeMounts:
        - name: theme
          mountPath: /var/www/html/adminer.css
          subPath: adminer.css
      volumes:
        - name: theme
          configMap:
            name: adminer
---
#kubectl create configmap adminer --from-file=./adminer.css
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: default
spec:
  selector:
    app: adminer
  ports:
  - name: adminer
    protocol: TCP
    port: 8091
    targetPort: 8080
