# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: default
type: Opaque
stringData:
  REPLICATION_USER: repliuser
  REPLICATION_PASSWORD: admin
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: postgres
