name: Update NetBird Image Tag

on:
  schedule:
    - cron: '0 0 */3 * *' # Runs automatically every 3 days
  workflow_dispatch:     # Allows you to click a button and run it manually

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: 🔎 Get current version from your repo
        id: get_current
        run: |
          # From netbird/nb.yaml 
          CURRENT_VERSION=$(sed -n 's/^[[:space:]]*image:[[:space:]]*[^:]*:\(.*\)/\1/p' netbird/nb.yaml)
          echo "Current version: $CURRENT_VERSION"
          echo "tag=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Fetch Latest NetBird Release
        id: get-version
        run: |
          # Query GitHub's API to find NetBird's absolute latest stable release tag
          LATEST_TAG=$(curl -s https://api.github.com/repos/netbirdio/netbird/releases/latest | jq -r '.tag_name | ltrimstr("v")')
          
          if [ "$LATEST_TAG" == "null" ] || ["$LATEST_TAG" == "$CURRENT_VERSION"]; then
            echo "ERROR: Failed to fetch release from GitHub API or no update came."
            exit 1
          fi
          
          echo "LATEST_VERSION=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest stable NetBird version found: $LATEST_TAG"

      - name: ✍️ Update netbird-version in nb.yaml
        run: |
          # Updates the file in repo with the new version tag
          sed -i 's|netbirdio/netbird:$CURRENT_VERSION|netbirdio/netbird:$LATEST_TAG|g' netbird/nb.yaml

      - name: ⬆️ Commit new version file
        uses: devops-infra/action-commit-push@v1.0.3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          commit_message: "Netbird image updated"
